name = "arbitrage-agent"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "AGENT"
class_name = "ArbitrageBot"

[[migrations]]
tag = "v1"
new_classes = ["ArbitrageBot"]
